import { BriefcaseBusiness, ChartNoAxesCombined, HeartPulse, Landmark, ScrollText, ShieldCheck } from 'lucide-react';
export const services=[
{slug:'financial-planning',title:'Financial Planning',icon:ChartNoAxesCombined,desc:'A structured view of your goals, risks and future needs.',items:['Financial needs analysis','Goal planning','Risk review','Protection planning','Long-term planning guidance','Follow-up consultation'],cta:'Start Financial Planning'},
{slug:'retirement-planning',title:'Retirement Planning',icon:Landmark,desc:'Plan for the income and confidence you want later in life.',items:['Retirement needs review','Income planning','Retirement savings discussion','Preservation planning','Retirement readiness check'],cta:'Plan for Retirement'},
{slug:'life-cover-protection',title:'Life Cover & Protection',icon:ShieldCheck,desc:'Understand how to protect your family, income and responsibilities.',items:['Life cover review','Disability cover discussion','Income protection needs','Family protection planning','Policy review support'],cta:'Check Your Cover Needs'},
{slug:'investments',title:'Investments',icon:ChartNoAxesCombined,desc:'Align your investment decisions with goals, timeframes and risk appetite.',items:['Investment goal review','Risk profile discussion','Long-term growth planning','Savings planning','Portfolio discussion'],cta:'Discuss Investment Options'},
{slug:'estate-legacy-planning',title:'Estate & Legacy Planning',icon:ScrollText,desc:'Create clarity around how your wealth and responsibilities are transferred.',items:['Estate planning discussion','Beneficiary planning','Legacy goals','Will and estate considerations','Family financial planning'],cta:'Plan Your Legacy'},
{slug:'business-planning',title:'Business & Professional Planning',icon:BriefcaseBusiness,desc:'Structured planning for business owners, professionals and executives.',items:['Business protection discussion','Key person cover needs','Executive planning','Professional income protection','Succession planning guidance'],cta:'Request Business Planning'}];
export const nav=[['About','/about'],['Services','/services'],['Resources','/resources'],['Contact','/contact']];
